project:
  type: website
  output-dir: docs

website:
  title: "Lab 3: COVID-19 Data Manipulation"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    self-contained: true

